export const PIPELINE_VERSION = 'property-pipeline-v9-owner-recovery'
export const NORMALIZER_VERSION = 'normalizer-v1'
export const CLASSIFIER_VERSION = 'intent-rules-v2-priced-owner'
export const CANDIDATE_VERSION = 'candidates-v7-project-labels'
export const PROMPT_VERSION = 'property-extractor-v1'
export const SCHEMA_VERSION = 'property-extraction-v1'
